# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.

# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/match.schema.json


 matches:


  # Print the current date
  - trigger: ";;date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  - trigger: ";;t-d"
    replace: "{{mytoday}}"
    vars:
      - name: mytoday
        type: date
        params:
          format: "%Y-%m-%d - "

  - trigger: ";;td"
    replace: "{{mytoday}}"
    vars:
      - name: mytoday
        type: date
        params:
          format: "%Y_%m_%d - "

  - trigger: ";;m"
    replace: "{{mymonth}}"
    vars:
      - name: mymonth
        type: date
        params:
          format: "%B Web Development"     # Full month name → June
          # format: "%b"   # Short month name → Jun
          # format: "%m"   # Numeric month → 06

  - trigger: ";;d"
    replace: "Web Development"



  # Print the output of a shell command
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"

  # Shopify Dev
  - trigger: ";;s"
    replace: "shopify theme dev"
  - trigger: ";;p"
    replace: "shopify theme pull"
  - trigger: ";;ks"
    replace: "lsof -ti:9292 | xargs kill -9"
  - trigger: ";;gitwork"
    replace: "git remote set-url origin git@github-work:nohermosa/ezexit.git"


  # Shopify Logins 
  - trigger: "loginvegan"
    replace: "shopify theme list -s vegan-treats-bakery.myshopify.com"
  - trigger: "loginootw"
    replace: "shopify theme list -s ootw2019.myshopify.com"
  - trigger: "loginapollo"
    replace: "shopify theme list -s apollo-neuro.myshopify.com"
  - trigger: "loginjuice"
    replace: "shopify theme list -s juiceshopsf.myshopify.com"
  - trigger: "logindrift"
    replace: "shopify theme list -s driftoriginals.myshopify.com"
  - trigger: "loginmv"
    replace: "shopify theme list -s marie-veronique-2.myshopify.com"
  - trigger: "loginez"
    replace: "shopify theme list -s ez-exit-van-accessories.myshopify.com"



  # Greetings
  - trigger: ";;ty"
    replace: "Thanks!\nMike"

  # And much more! For more information, visit the docs: https://espanso.org/docs/
