# Starship Configuration

format = """
$username$hostname→ $directory$git_branch$git_status\
$line_break\
$character """

# Right side prompt
right_format = ""

add_newline = true

[character]
success_symbol = "[>](#c2876c bold)"
error_symbol = "[>](#c2876c bold)"

[username]
show_always = true
format = "[$user](#8a9630 bold)"
style_user = "#8a9630 bold"

[hostname]
ssh_only = false
format = "[@$hostname](#8a9630 bold) "
style = "#8a9630 bold"

[directory]
truncation_length = 10
truncate_to_repo = false 
format = "[$path]($style) "
style = "#4d8283 bold"
read_only = " [RO]"
read_only_style = "red"
home_symbol = "~"

[git_branch]
symbol = "* "
format = "on [$symbol$branch]($style) "
style = "#8a9630 bold"


[git_status]
conflicted = '🏳'
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
up_to_date = '✓'
untracked = '🤷'
stashed = '📦'
modified = '📝'
staged = '[++\($count\)](green)'
renamed = '👅'
deleted = '🗑'
